### ISSUE TITLE
Initialization inconsistent with BERT

### ISSUE THREAD

**Issue by karlstratos** [WenzhengZhang/hard-nce-el#3]
https://github.com/WenzhengZhang/hard-nce-el/blob/726b8401410c2e88de8b37616d9bfb1532e3947b/zeshel/retrieval/model.py#L128

**Comment by WenzhengZhang** [comment]
Thanks! Modified here
https://github.com/WenzhengZhang/hard-nce-el/blob/2f4c62d171b442f9aaf7c030d1a233936e414ece/retriever.py#L127
